### ISSUE TITLE
ES NECESARIO ACTUALIZAR LA CLASE

### ISSUE THREAD

**Issue by realaceone** [VIDALYCONTRERASLIMITADA/REST#5]
Se publicó el servicio de emails en la API Valora. El método aceptado para enviar es sólo por POST, debido al estándar RESTFul. De acuerdo a esto, se hace necesario actualizar la clase REST:

## Requerimientos
- Se debe agregar método POST.
- Envío de Params, en caso de ser POST, se debe construir a través del método **setParameterPost**
- La construcción de la clase **Zend_Http_Client** se debe mejorar. Existen configuraciones que se deben agregar para mejorar el envío / recepción de información, etc.
 - Para más información de este punto, referirse al manual de[ Zend 1.12](https://framework.zend.com/manual/1.12/en/zend.http.client.html)

**Comment by jonyram1988** [comment]
SE cierra.
